services:
  pg_crypto:
    image: postgres:15
    ports:
      - '5432:5432'
    networks:
      - eltnetwork
    environment:
      POSTGRES_DB: crypto_db
      POSTGRES_USER: icanooo
      POSTGRES_PASSWORD: rahasia
    volumes:
      - pgdata:/var/lin/postgresql/data

  python_script:
    build:
      context: ./elt
      dockerfile: Dockerfile
    command: ["python", "script.py"]
    networks:
      - eltnetwork
    depends_on:
      - pg_crypto

  pg_airflow:
    image: postgres:15
    networks:
      - eltnetwork
    environment:
      POSTGRES_DB: airflow_db
      POSTGRES_USER: icanooo_airflow
      POSTGRES_PASSWORD: rahasia
    

  airflow_init:
    image: apache/airflow:latest
    depends_on:
      - pg_crypto
    networks:
      - eltnetwork
    environment:
      - AIRFLOW__DATABASE_SQL_ALCHEMY_CONN=pg_airflow+psycopg2://icanooo_airflow:rahasia@postgres/airflow_db
    command: >
      bash -c "airflow db init &&
              airflow users create --username icanooo --password rahasia --firstname Muhammad --lastname ihsan --role Admin --email muhihsan0@outlook.com"

networks:
  eltnetwork:
    driver: bridge

volumes:
  pgdata:
