services:
  pg_crypto:
    image: postgres:15
    ports:
      - '5434:5432'
    networks:
      - eltnetwork
    environment:
      POSTGRES_DB: crypto_db
      POSTGRES_USER: icanooo
      POSTGRES_PASSWORD: icanacin

  python_script:
    build:
      context: ./elt
      dockerfile: Dockerfile
    command: ["python", "script.py"]
    networks:
      - eltnetwork
    depends_on:
      - pg_crypto

networks:
  eltnetwork:
    driver: bridge
